import React from 'react'
import {useRouter} from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Faq from './faq'

const inter = Inter({ subsets: ['latin'] })

 const greetings = () => {
    const router = useRouter();
    const {greetings} = router.query;
    const showGreetings = greetings ? `Hello ${greetings}!!! Welcome to the blog` : 'Welcome to the blog';
  return (
    <>

      <style jsx>
        {`
            .slp{
              font-family: ${inter};
              background-color: red;
            }

            nav{
              background-color: red;
            }
        
        `}

      </style>
        <Head>
        <title>{`Hunting Blog ${greetings || " "}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className='slp'>index page</p>
      

       


       <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
      <div>
      <h2>{showGreetings}</h2>
        <h2>Coding blog by shetty</h2>
      </div>
     </div>

     <div className={styles.center}>
        
          <Image
            className={styles.logo}
            src="/img.jpeg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          /> 

<h1>Coding blog</h1>
        </div>

        <div>
          <p>Welcome to the Coding blog! Here you can find articles about coding.</p>
          
          </div>  


            
        <Faq/>
      </main>    

    </>
  )
}

export default greetings;




      

      
     
     
          
          

        


 